# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import routeGuide_pb2 as routeGuide__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in routeGuide_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouteGuideStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createDocument = channel.unary_unary(
                '/RouteGuide/createDocument',
                request_serializer=routeGuide__pb2.createDocumentRequest.SerializeToString,
                response_deserializer=routeGuide__pb2.createDocumentResponse.FromString,
                _registered_method=True)
        self.getDocument = channel.unary_unary(
                '/RouteGuide/getDocument',
                request_serializer=routeGuide__pb2.getDocumentRequest.SerializeToString,
                response_deserializer=routeGuide__pb2.getDocumentResponse.FromString,
                _registered_method=True)
        self.editDocument = channel.unary_unary(
                '/RouteGuide/editDocument',
                request_serializer=routeGuide__pb2.editDocumentRequest.SerializeToString,
                response_deserializer=routeGuide__pb2.editDocumentResponse.FromString,
                _registered_method=True)
        self.subscribeToUpdates = channel.unary_stream(
                '/RouteGuide/subscribeToUpdates',
                request_serializer=routeGuide__pb2.updateRequest.SerializeToString,
                response_deserializer=routeGuide__pb2.documentUpdate.FromString,
                _registered_method=True)


class RouteGuideServicer:
    """Missing associated documentation comment in .proto file."""

    def createDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def editDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subscribeToUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.createDocument,
                    request_deserializer=routeGuide__pb2.createDocumentRequest.FromString,
                    response_serializer=routeGuide__pb2.createDocumentResponse.SerializeToString,
            ),
            'getDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.getDocument,
                    request_deserializer=routeGuide__pb2.getDocumentRequest.FromString,
                    response_serializer=routeGuide__pb2.getDocumentResponse.SerializeToString,
            ),
            'editDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.editDocument,
                    request_deserializer=routeGuide__pb2.editDocumentRequest.FromString,
                    response_serializer=routeGuide__pb2.editDocumentResponse.SerializeToString,
            ),
            'subscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribeToUpdates,
                    request_deserializer=routeGuide__pb2.updateRequest.FromString,
                    response_serializer=routeGuide__pb2.documentUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RouteGuide', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouteGuide:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RouteGuide/createDocument',
            routeGuide__pb2.createDocumentRequest.SerializeToString,
            routeGuide__pb2.createDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RouteGuide/getDocument',
            routeGuide__pb2.getDocumentRequest.SerializeToString,
            routeGuide__pb2.getDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def editDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RouteGuide/editDocument',
            routeGuide__pb2.editDocumentRequest.SerializeToString,
            routeGuide__pb2.editDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def subscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/RouteGuide/subscribeToUpdates',
            routeGuide__pb2.updateRequest.SerializeToString,
            routeGuide__pb2.documentUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
