# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeGuide.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'routeGuide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10routeGuide.proto\"9\n\x15\x63reateDocumentRequest\x12\x0f\n\x07\x64ocName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"(\n\x16\x63reateDocumentResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"%\n\x12getDocumentRequest\x12\x0f\n\x07\x64ocName\x18\x01 \x01(\t\"7\n\x13getDocumentResponse\x12\x0f\n\x07\x64ocName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"I\n\x13\x65\x64itDocumentRequest\x12\x0f\n\x07\x64ocName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x01(\x05\"8\n\x14\x65\x64itDocumentResponse\x12\x0f\n\x07\x64ocName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\" \n\rupdateRequest\x12\x0f\n\x07\x64ocName\x18\x01 \x01(\t\"2\n\x0e\x64ocumentUpdate\x12\x0f\n\x07\x64ocName\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\x87\x02\n\nRouteGuide\x12\x43\n\x0e\x63reateDocument\x12\x16.createDocumentRequest\x1a\x17.createDocumentResponse\"\x00\x12:\n\x0bgetDocument\x12\x13.getDocumentRequest\x1a\x14.getDocumentResponse\"\x00\x12=\n\x0c\x65\x64itDocument\x12\x14.editDocumentRequest\x1a\x15.editDocumentResponse\"\x00\x12\x39\n\x12subscribeToUpdates\x12\x0e.updateRequest\x1a\x0f.documentUpdate\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeGuide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEDOCUMENTREQUEST']._serialized_start=20
  _globals['_CREATEDOCUMENTREQUEST']._serialized_end=77
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_start=79
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_end=119
  _globals['_GETDOCUMENTREQUEST']._serialized_start=121
  _globals['_GETDOCUMENTREQUEST']._serialized_end=158
  _globals['_GETDOCUMENTRESPONSE']._serialized_start=160
  _globals['_GETDOCUMENTRESPONSE']._serialized_end=215
  _globals['_EDITDOCUMENTREQUEST']._serialized_start=217
  _globals['_EDITDOCUMENTREQUEST']._serialized_end=290
  _globals['_EDITDOCUMENTRESPONSE']._serialized_start=292
  _globals['_EDITDOCUMENTRESPONSE']._serialized_end=348
  _globals['_UPDATEREQUEST']._serialized_start=350
  _globals['_UPDATEREQUEST']._serialized_end=382
  _globals['_DOCUMENTUPDATE']._serialized_start=384
  _globals['_DOCUMENTUPDATE']._serialized_end=434
  _globals['_ROUTEGUIDE']._serialized_start=437
  _globals['_ROUTEGUIDE']._serialized_end=700
# @@protoc_insertion_point(module_scope)
